### ISSUE TITLE
Feature: add icons to features section

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TAKANOME-DEV/BlogHive#22]
### Type of feature

🍕 Feature

### Current behavior

This is what the features section looks like:

![key_features](https://user-images.githubusercontent.com/79809121/210829877-3c83ea4a-4b79-405b-906a-50df580134ca.png)

### Suggested solution

- remove border
- install [React Icons](https://react-icons.github.io/react-icons/)
- replace the text placeholder `icon` with an icon (see screenshot)
- Don't change the card background (for now)
![key_features_xd](https://user-images.githubusercontent.com/79809121/210830533-713e0cf7-84ec-4de6-a0da-07271759098d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TAKANOME-DEV** [comment]
Not yet, do you want to take it?

**Comment by jayanth-kumar-morem** [comment]
I would love to contribute. Can you assign me to this?

**Comment by dev-phantom** [comment]
yea i would love to take it

**Comment by TAKANOME-DEV** [comment]
sorry @jayanth-kumar-morem, please have a look at the other issues and let me know if you need more infos or any guidance

**Comment by dev-phantom** [comment]
@TAKANOME-DEV what  is the background gradient used here 
and i would love  to suggest that the text on that background is not very visible

**Comment by TAKANOME-DEV** [comment]
I think it a blue color mixed with teal: use `bg-gradient-to-r from-blue-600 to-teal-300` and try playing with the colors to see :eyes:

Suggestions are welcome :pray: 

You can also have a look at https://www.figma.com/file/OI6kqMhO65Eh5LXC40uuOH/BlogHive?node-id=27%3A2&t=nqy5OoBrHYmzHPxf-0

**Comment by dev-phantom** [comment]
Ok i'll try to fix this now
