### ISSUE TITLE
Feature: update text size and color for the subscribe card

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TAKANOME-DEV/BlogHive#24]
### Type of feature

🍕 Feature

### Current behavior

![subscribe](https://user-images.githubusercontent.com/79809121/210833307-56be6999-9f10-4c5c-8cfb-8d0e45072b0b.png)

### Suggested solution

- Change bg color to match the screenshot below (use `bg-slate-300`)
- change text size

![subscribe_xd](https://user-images.githubusercontent.com/79809121/210833564-ed4eb5ef-5c4d-41a1-b300-511b91f51518.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-phantom** [comment]
assign me to this also

**Comment by TAKANOME-DEV** [comment]
Sure, thanks for taking it :pray:
