### ISSUE TITLE
Feature: update input and button components

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TAKANOME-DEV/BlogHive#25]
### Type of feature

🍕 Feature

### Current behavior

![input_newsletter](https://user-images.githubusercontent.com/79809121/210837220-3c8a148b-8aae-4724-9a31-03ce728a6aa5.png)

### Suggested solution

- Create a reusable input component inside `components/atoms`
- Change the button type (see screenshot)

:information_source: The button can be outside of the input for now

Final Result:

![input_newsletter_xd](https://user-images.githubusercontent.com/79809121/210837628-9d1676c0-154d-497d-8bbe-b90598b7544c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-phantom** [comment]
please assign me to this

**Comment by TAKANOME-DEV** [comment]
Currently, we don't have the `atoms` folder in `components`.
PR #21 needs to be merged before addressing this issue.
