### ISSUE TITLE
Feature: Update footer links

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TAKANOME-DEV/BlogHive#27]
### Type of feature

🍕 Feature

### Current behavior

![footer_links](https://user-images.githubusercontent.com/79809121/210839496-4f976a03-352a-4b9f-ae3d-4aa389d5bdb1.png)

### Suggested solution

Update links position and sizes to match the image below

![footer_links_xd](https://user-images.githubusercontent.com/79809121/210839978-7053d080-aff7-49cc-a3b1-62b022ba07ff.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by favourite1975** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
@favourite1975 thanks for your interest in contributing i tohis project.
Let me know if you have any question

**Comment by dev-phantom** [comment]
please what is the hex-color for this?
or is it blue-600
