### ISSUE TITLE
Feature: Add responsiveness for smaller devices

### ISSUE THREAD

**Issue by dev-phantom** [TAKANOME-DEV/BlogHive#31]
### Type of feature

🍕 Feature

### This is  the current behaviour 
![image](https://user-images.githubusercontent.com/72051159/211088578-46732c69-7109-4be0-a9fc-af9309c3e5f6.png)

### Suggested solution

Break points for different devices should  be  defined in the tailwind.config.js file 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-phantom** [comment]
![image](https://user-images.githubusercontent.com/72051159/211149541-518c77a0-8a26-4861-ac61-690566de3968.png)

i think `flex-col lg:flex-row` should be added to the footer tag to fix this

**Comment by TAKANOME-DEV** [comment]
Yeah, it's not responsive at all. Also, the padding should be decreased for mobile.
